apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: devops.ram.com
spec:
  group: ram.com
  scope: Namespaced
  names:
    kind: Devops
    plural: devops
    singular: devop
    shortNames:
      - ram
      - yash
      - fire
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                  description: "this is the name of devops"
                age:
                  type: integer
                  description: "this is the age of devops"