kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apache-manager
  namespace: apache
rules:
- apiGroups: ["","batch","rbac.authorization.k8s.io"]
  resources: ["pods","services","deployments"]
  verbs: ["get","delete","apply","watch","create","patch"]